### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by itsmedhaaz** [farhanmansurii/my-project#1]
Sir, Can u make the Homepage have options, such as Trending Movies, Trending Series, and Category selection options? Using TMDB API

**Comment by itsmedhaaz** [comment]
No response 🤣

**Comment by farhanmansurii** [comment]
Yes i can and i might do it i just didnt add it to make it fast asap LMAO

**Comment by shiyiya** [comment]
🥳

**Comment by farhanmansurii** [comment]
> 🥳

broo thanks for the player ngl blessing
